### ISSUE TITLE
Pods-Environment.h file be found

### ISSUE THREAD

**Issue by JAStanton** [crushlovely/Amaro#32]
OSX 10.10.5, fresh install a few minutes this is what I get:

<img width="725" alt="screen shot 2015-09-19 at 5 57 38 pm" src="https://cloud.githubusercontent.com/assets/645300/9978717/f4078104-5ef7-11e5-8cb4-ce43a386fb0b.png">

<img width="258" alt="screen shot 2015-09-19 at 5 57 57 pm" src="https://cloud.githubusercontent.com/assets/645300/9978718/fd7f42e4-5ef7-11e5-8ecd-b913a849d3c3.png">

I can comment out the import but I think none of my macros defined in this file will be correct :P (It builds just fine when I comment it out however)

**Comment by JAStanton** [comment]
Pod version 0.38.2

**Comment by JAStanton** [comment]
And if I git clone your repo, `pods install` and try to build I get the same error :-/

**Comment by misterfifths** [comment]
@JAStanton Hey! Sorry for the long, long response time. Yah, Cocoapods retired that Environment file a while ago, so I've had to work around it. I'm sure you've probably moved on, but the newly release 1.0.0 of Amaro deals with this. Thanks for raising the issue!
