### ISSUE TITLE
The Crashlytics binary (/Applications/Fabric.app/Contents/MacOS/Crashlytics) is not readable

### ISSUE THREAD

**Issue by JAStanton** [crushlovely/Amaro#33]
So the app is called Fabric now, and I'm sure some work will be needed to integrate with it

**Comment by misterfifths** [comment]
It was such a hack to get Crashlytics going in the first place, I'm not up for it with Fabric. I don't like the approach they're taking of a monolithic hands-off thing anyway. Crashlytics support has been stripped from 1.0.0, so I'm going to close this.
